### ISSUE TITLE
DataTables Rework

### ISSUE THREAD

**Issue by boumi21** [boumi21/mkwtas-website#2]
Actual Datatables is in version 1.10.19

## TODO
Need to upgrade to latest version https://cdn.datatables.net/releases.html

- [ ] Verify that there is no breking changes
- [ ] Check if new features could be interesting
- [ ] Test & implement new features if needed
